apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kie-cloud-operator
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consoleclidownloads
  - consoleexternalloglinks
  - consolelinks
  - consolenotifications
  - consoleyamlsamples
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete

