apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kie-cloud-operator
subjects:
- kind: ServiceAccount
  namespace: ms-test
  name: kie-cloud-operator
roleRef:
  kind: ClusterRole
  name: kie-cloud-operator
  apiGroup: rbac.authorization.k8s.io
